import {UserChats} from "./userChats.model";

export interface User {
  id?: string,
  nick?: string,
  avatar?: string,
  background?: string,
  bio?: string,
  realName?: string,
  language?: string,
  country?: string,
  gender?: string,
  books?: string[],
  ebooks?: string[],
  images?: string[],
  choosenBooks?: string[],
  onHold?: string[],
  planToRead?: string[],
  read?: string[],
  reading?: string[],
  dropped?: string[],
  followers?: string[],
  groups?: string[],
  chats?: UserChats[],
  isPremium?: boolean,
  untilPremium?: any,
  joinDate?: any,
  birthDate?: any,
  reviews?: string[],
  invitations?: string[],
  favouritesBooks?: string[],
  readPoints?: number,
  writePoints?: number
}
